'use strict';

module.exports = [
  {name: 'Barcamp Candidate 1', child: 'UI/UX'},
  {name: 'Barcamp Candidate 2', child: 'Design'},
  {name: 'Barcamp Candidate 3', child: 'Develop'},
  {name: 'Barcamp Candidate 4', child: 'Testing'},
  {name: 'Modern Testing Technologies or how to avoid getting murdered in your sleep by a death goblin', child: 'Testing'},
  {name: 'An Android Journey', child: 'Design'},
  {name: 'AST Transformations, How to avoid write less code', child: 'Develop'},
  {name: 'Maps n Apps', child: 'Develop'},
  {name: 'Bitchy App Clinic', child: 'UI/UX'},
  {name: 'TDD Coverage', child: 'Testing'},
  {name: 'The Killer design specs', child: 'Design'},
  {name: 'Intel INDIE', child: 'Develop'},
  {name: 'Security', child: 'Develop'},
  {name: 'Cupboard Persistance', child: 'Develop'},
  {name: 'From Legacy Code to Hexagonal Android', child: 'Develop'},
  {name: 'Intents system', child: 'Develop'},
  {name: 'Connecting android to a Cloud Backend', child: 'Develop'},
  {name: 'AOSP Building Blocks', child: 'Develop'},
  {name: 'Build Your Gradle Plugin', child: 'Develop'},
  {name: 'Calligraphy – Fonts in styling', child: 'Design'},
  {name: 'Better data transport with Gradle', child: 'Develop'},
  {name: 'Things App Developers Do', child: 'Develop'},
  {name: 'Gradle', child: 'Develop'},
  {name: 'Putting the magic touch on your app with custom views', child: 'Design'},
  {name: 'The death of the refresh button', child: 'UI/UX'},
  {name: 'Y U NO CRAFTSMAN!?', child: 'Develop'},
  {name: 'Genymotion – The leaked session', child: 'Develop'},
  {name: 'Running your own license server', child: 'Develop'},
  {name: 'What’s New in Android', child: 'Develop'},
  {name: 'Papercraft: Material design & implementation', child: 'Design'},
  {name: 'Gradlin’: Plugging it in for build success', child: 'Develop'},
  {name: 'Fighting application size with ProGuard and beyond', child: 'Develop'},
  {name: 'Climbing over the Great Wall: Lessons to learn from China’s most successful Android games', child: 'Develop'},
  {name: 'Video Streaming: from the native Android player to uncoventional devices', child: 'Develop'},
  {name: 'Dear developers, design details matter', child: 'Design'},
  {name: 'Engineering for Android scale at SoundCloud', child: 'Develop'},
  {name: 'Size does not matter, 2.83 inches is enough', child: 'Develop'},
  {name: 'Connect your mobile apps to the cloud the easy way', child: 'Develop'},
  {name: 'Going beyond smartphones', child: 'Develop'},
  {name: 'The Importance of Feedback in User Interface Design', child: 'Design'},
  {name: 'If I can, you can too – Animations for developers', child: 'Design'},
  {name: 'How to Build a One Man Band', child: 'Develop'},
  {name: 'Death to Passwords', child: 'Develop'},
  {name: 'Using the Android NDK', child: 'Develop'},
  {name: 'Introduction to Android Wear – A Glimpse Into the Future', child: 'Develop'},
  {name: 'Graphical Magic', child: 'Design'},
  {name: 'Testing applications at Facebook', child: 'Testing'},
  {name: 'Android Key Management', child: 'Develop'},
  {name: 'Designing Accessible Android Applications', child: 'Design'},
  {name: 'Fun with Custom Layouts', child: 'Design'},
  {name: 'Rx-Fy all the things!', child: 'Develop'},
  {name: 'Reversing Engineering Android applications (and protecting them)', child: 'Develop'},
  {name: 'How to improve android app performance with the new ART Runtime and Dalvik VM', child: 'Develop'},
  {name: 'Responsive Game Design: Bringing Desktop and Mobile Games to the Living Room', child: 'Develop'},
  {name: 'Getting By With Less Than 1.21 Gigawatts (“Project Volta”)', child: 'Develop'},
  {name: 'Fun with Android Shaders and Filters', child: 'Develop'},
  {name: 'How to build rock-solid apps and keep 100M+ users happy', child: 'Develop'},
  {name: 'It’s not a bug, it’s a feature', child: 'Develop'},
  {name: 'Creating the Internet of My Things with Bluetooth Smart', child: 'Develop'},
  {name: 'Deep Dive into the Gradle-based Android Build System', child: 'Develop'},
  {name: 'Framing the Canvas', child: 'Design'},
  {name: 'Playing outside the sandbox – Developing on CyanogenMod', child: 'Develop'},
  {name: 'What’s new in Android Testing', child: 'Testing'},
  {name: 'Android Industrial Mobility', child: 'Develop'}
];
